spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ashokit_ecomm
    username: root
    password: admin
  boot:
    admin:
      client:
        url: http://localhost:1111/
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  
  
