spring:
  application:
    name: Auth-Service
  datasource:
    password: admin
    url: jdbc:mysql://localhost:3306/sbms39
    username: root 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  
server:
  port: 8081
  
  
