spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ashokit_ecomm
    username: root
    password: admin
  boot:
    admin:
      client:
        url: http://localhost:1111/
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8081
  
  
auth-service:
  messages:
    userReg: User Created
    userRegErr: User Creation Failed
    login: Login Success
    loginErr: Invalid Credentials
  
  
